compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

yarnPath: .yarn/releases/yarn-4.6.0.cjs
